apiVersion: v1
kind: Pod
metadata:
  name: webcam
spec:
  containers:
  - name: webcam
    image: kojiha/webcam
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/video0
      name: video
  volumes:
  - name: video
    hostPath:
      path: /dev/video0
